name: CI

on: [push, pull_request]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm install
      - run: npm run set-claim-code

  build:
    runs-on: ubuntu-latest
    services:
      plex:
        image: plexinc/pms-docker@latest
        ports:
          - 32400:32400
        env:
          PLEX_CLAIM: ${{ steps.pre-build.outputs.PLEX_CLAIM }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm install
      - run: npm run set-claim-code

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: Atrox/codecov-action@master
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
